### ISSUE TITLE
install instructions add ruby

### ISSUE THREAD

**Issue by plattrap** [tresacton/dspectrum#2]
Could you add that this needs ruby to run?
`sudo apt-get install ruby`

Also the gem install step needs `sudo` under Ubuntu.

**Comment by tresacton** [comment]
Ruby is listed along with Inspectrum under the header "Prerequisites" in the Readme. 

You needed to sudo because you were attempting to install the gem to the "system" Ruby. As a (generally) better practice you may wish to use RVM instead of apt to manage the Ruby versions on your system.

Perhaps the Readme should be updated to better cater for users who are new to dependency management for libraries like these. Thanks for the suggestion. As soon as I have more time I will give the Readme an overhaul or create a bootstrapping script.

**Comment by tresacton** [comment]
Closing issue as this app is no longer maintained. New app at: https://github.com/tresacton/dspectrumgui
